[package]
name = "cross-host-communication"
edition = "2021"
publish = false

[dependencies]
iceoryx2 = { git = "https://github.com/eclipse-iceoryx/iceoryx2", branch = "main" }
iceoryx2-link = { git = "https://github.com/eclipse-iceoryx/iceoryx2", branch = "main" }
iceoryx2-link-tunnel = { git = "https://github.com/eclipse-iceoryx/iceoryx2", branch = "main" }
iceoryx2-integrations-zenoh-link-carrier = { git = "https://github.com/eclipse-iceoryx/iceoryx2", branch = "main" }
zenoh = { version = "1.9" }
